version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - sonarr-config:/config
      - /home/briand/jellyfin/media/TV_Series:/tv
      - /home/briand/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
volumes:
  sonarr-config:
