version: "2.1"
services:

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      # This can grown large, 50gb+ for a large collection
      - ../containers-data/jellyfin-config:/config
      - ../media/tvshows:/data/tvshows
      - ../media/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../containers-data/jackett-config:/config
        #- ../containers-data/jackett-downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - ../containers-data/transmission-config:/config
      - ../downloads:/downloads
      - ../downloads:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
