version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - ./media:/media
    restart: unless-stopped

volumes:
  jellyfin-config:
  jellyfin-cache:
