version: "2.1"
services:

  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      # This can grown large, 50gb+ for a large collection
      - /media/usb/appdata/jellyfin-config:/config
      - /media/usb/appdata/jellyfin-cache:/cache
      - /media/usb/media/tvshows:/media/tvshows
      - /media/usb/media/movies:/media/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /media/usb/appdata/sonarr-config:/config
      - /media/usb/media/tvshows:/tv
      - ../containers-data/transmission-downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /media/usb/appdata/radarr-config:/config
      - /media/usb/media/movies:/movies
      - ../containers-data/transmission-downloads/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /media/usb/appdata/nzbget-config:/config
      - ../containers-data/nzbget-downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - ../containers-data/transmission-config:/config
      - ../containers-data/transmission-downloads:/downloads
      - ../containers-data/transmission-watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - ../containers-data/jackett-config:/config
      - ../containers-data/jackett-downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

